name: "Merge Monitor"
description: "Blocks PRs that modify sensitive files unless labeled"
inputs:
  bypass_label:
    description: "Label that allows bypassing the file check"
    required: false
    default: "allow-sensitive-change"

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run merge monitor check
      run: |
        python ${{ github.action_path }}/check.py
      shell: bash
      env:
        BYPASS_LABEL: ${{ inputs.bypass_label }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use secrets to ensure token is passed correctly
        GITHUB_REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
