name: Merge Monitor

on:
  pull_request:
    types: [open, synchronize, reopened, labeled]

jobs:
  check_sensitive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Merge Monitor
        uses: ./.github/actions/check-sensitive-files
        with:
          bypass_label: "allow-sensitive-change"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
