name: "Merge Monitor"
description: "Blocks PRs that modify sensitive files unless labeled"
inputs:
  bypass_label:
    description: "Label that allows bypassing the file check"
    required: false
    default: "allow-sensitive-change"

runs:
  using: 'composite'
  steps:
    - run: |
        pip install requests
        python3 ${{ github.action_path }}/check.py
      shell: bash
      env:
        BYPASS_LABEL: ${{ inputs.bypass_label }}
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}

