name: Merge Monitor

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-sensitivity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run custom check-sensitive-files action
        uses: ./path-to-your-action
        with:
          bypass_label: 'skip-sensitive-check'  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
